// <auto-generated />
using System;
using AkarSoftware.HospitalApp.Repositories.Concrete.EntityFramework.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AkarSoftware.HospitalApp.Repositories.Migrations
{
    [DbContext(typeof(MyContexts))]
    partial class MyContextsModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AkarSoftware.HospitalApp.Entities.Concrete.Identities.AppMenus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActionParameters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AppModulesId")
                        .HasColumnType("int");

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ControllerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<string>("IconName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MenuDesctiption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MenuName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RootMenusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppModulesId");

                    b.HasIndex("RootMenusId");

                    b.ToTable("AppMenus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActionName = "Randevu Al",
                            ActionParameters = "",
                            AppModulesId = 1,
                            AreaName = "Randevu Al",
                            ControllerName = "Randevu Al",
                            CreatedDate = new DateTime(2024, 4, 6, 23, 33, 24, 916, DateTimeKind.Local).AddTicks(8172),
                            CreatedUser = "APP",
                            CreatedUserId = 0,
                            IconName = "Randevu Al",
                            IsActive = true,
                            MenuDesctiption = "Randevu Al",
                            MenuName = "Randevu Al",
                            ModifiedDate = new DateTime(2024, 4, 6, 23, 33, 24, 916, DateTimeKind.Local).AddTicks(8186),
                            ModifiedUserId = 0,
                            ModifiedUserName = "APP"
                        },
                        new
                        {
                            Id = 2,
                            ActionName = "Kurumsal",
                            ActionParameters = "",
                            AppModulesId = 1,
                            AreaName = "Kurumsal",
                            ControllerName = "Kurumsal",
                            CreatedDate = new DateTime(2024, 4, 6, 23, 33, 24, 916, DateTimeKind.Local).AddTicks(8189),
                            CreatedUser = "APP",
                            CreatedUserId = 0,
                            IconName = "Kurumsal",
                            IsActive = true,
                            MenuDesctiption = "",
                            MenuName = "Kurumsal",
                            ModifiedDate = new DateTime(2024, 4, 6, 23, 33, 24, 916, DateTimeKind.Local).AddTicks(8189),
                            ModifiedUserId = 0,
                            ModifiedUserName = "APP"
                        },
                        new
                        {
                            Id = 3,
                            ActionName = "Hakkımızda",
                            ActionParameters = "",
                            AppModulesId = 1,
                            AreaName = "Hakkımızda",
                            ControllerName = "Hakkımızda",
                            CreatedDate = new DateTime(2024, 4, 6, 23, 33, 24, 916, DateTimeKind.Local).AddTicks(8192),
                            CreatedUser = "APP",
                            CreatedUserId = 0,
                            IconName = "Hakkımızda",
                            IsActive = true,
                            MenuDesctiption = "",
                            MenuName = "Hakkımızda",
                            ModifiedDate = new DateTime(2024, 4, 6, 23, 33, 24, 916, DateTimeKind.Local).AddTicks(8192),
                            ModifiedUserId = 0,
                            ModifiedUserName = "APP",
                            RootMenusId = 2
                        },
                        new
                        {
                            Id = 4,
                            ActionName = "Misyon",
                            ActionParameters = "",
                            AppModulesId = 1,
                            AreaName = "Misyon",
                            ControllerName = "Misyon",
                            CreatedDate = new DateTime(2024, 4, 6, 23, 33, 24, 916, DateTimeKind.Local).AddTicks(8194),
                            CreatedUser = "APP",
                            CreatedUserId = 0,
                            IconName = "Misyon",
                            IsActive = true,
                            MenuDesctiption = "",
                            MenuName = "Misyon",
                            ModifiedDate = new DateTime(2024, 4, 6, 23, 33, 24, 916, DateTimeKind.Local).AddTicks(8195),
                            ModifiedUserId = 0,
                            ModifiedUserName = "APP",
                            RootMenusId = 3
                        },
                        new
                        {
                            Id = 5,
                            ActionName = "Vizyon",
                            ActionParameters = "",
                            AppModulesId = 1,
                            AreaName = "Vizyon",
                            ControllerName = "Vizyon",
                            CreatedDate = new DateTime(2024, 4, 6, 23, 33, 24, 916, DateTimeKind.Local).AddTicks(8197),
                            CreatedUser = "APP",
                            CreatedUserId = 0,
                            IconName = "Vizyon",
                            IsActive = true,
                            MenuDesctiption = "",
                            MenuName = "Vizyon",
                            ModifiedDate = new DateTime(2024, 4, 6, 23, 33, 24, 916, DateTimeKind.Local).AddTicks(8198),
                            ModifiedUserId = 0,
                            ModifiedUserName = "APP",
                            RootMenusId = 3
                        },
                        new
                        {
                            Id = 6,
                            ActionName = "Kariyer",
                            ActionParameters = "",
                            AppModulesId = 1,
                            AreaName = "Kariyer",
                            ControllerName = "Kariyer",
                            CreatedDate = new DateTime(2024, 4, 6, 23, 33, 24, 916, DateTimeKind.Local).AddTicks(8200),
                            CreatedUser = "APP",
                            CreatedUserId = 0,
                            IconName = "Kariyer",
                            IsActive = true,
                            MenuDesctiption = "",
                            MenuName = "Kariyer",
                            ModifiedDate = new DateTime(2024, 4, 6, 23, 33, 24, 916, DateTimeKind.Local).AddTicks(8201),
                            ModifiedUserId = 0,
                            ModifiedUserName = "APP",
                            RootMenusId = 3
                        },
                        new
                        {
                            Id = 7,
                            ActionName = "Sonuçlar",
                            ActionParameters = "",
                            AppModulesId = 1,
                            AreaName = "Sonuçlar",
                            ControllerName = "Sonuçlar",
                            CreatedDate = new DateTime(2024, 4, 6, 23, 33, 24, 916, DateTimeKind.Local).AddTicks(8203),
                            CreatedUser = "APP",
                            CreatedUserId = 0,
                            IconName = "Sonuçlar",
                            IsActive = true,
                            MenuDesctiption = "",
                            MenuName = "Sonuçlar",
                            ModifiedDate = new DateTime(2024, 4, 6, 23, 33, 24, 916, DateTimeKind.Local).AddTicks(8203),
                            ModifiedUserId = 0,
                            ModifiedUserName = "APP"
                        },
                        new
                        {
                            Id = 8,
                            ActionName = "Reçete",
                            ActionParameters = "",
                            AppModulesId = 1,
                            AreaName = "Reçete",
                            ControllerName = "Reçete",
                            CreatedDate = new DateTime(2024, 4, 6, 23, 33, 24, 916, DateTimeKind.Local).AddTicks(8205),
                            CreatedUser = "APP",
                            CreatedUserId = 0,
                            IconName = "Reçete",
                            IsActive = true,
                            MenuDesctiption = "",
                            MenuName = "Reçete",
                            ModifiedDate = new DateTime(2024, 4, 6, 23, 33, 24, 916, DateTimeKind.Local).AddTicks(8206),
                            ModifiedUserId = 0,
                            ModifiedUserName = "APP",
                            RootMenusId = 7
                        },
                        new
                        {
                            Id = 9,
                            ActionName = "Tahlil",
                            ActionParameters = "",
                            AppModulesId = 1,
                            AreaName = "Tahlil ",
                            ControllerName = "Tahlil",
                            CreatedDate = new DateTime(2024, 4, 6, 23, 33, 24, 916, DateTimeKind.Local).AddTicks(8208),
                            CreatedUser = "APP",
                            CreatedUserId = 0,
                            IconName = "Tahlil",
                            IsActive = true,
                            MenuDesctiption = "",
                            MenuName = "Tahlil",
                            ModifiedDate = new DateTime(2024, 4, 6, 23, 33, 24, 916, DateTimeKind.Local).AddTicks(8209),
                            ModifiedUserId = 0,
                            ModifiedUserName = "APP",
                            RootMenusId = 7
                        },
                        new
                        {
                            Id = 10,
                            ActionName = "Doktorlar",
                            ActionParameters = "",
                            AppModulesId = 1,
                            AreaName = "Doktorlar",
                            ControllerName = "Doktorlar",
                            CreatedDate = new DateTime(2024, 4, 6, 23, 33, 24, 916, DateTimeKind.Local).AddTicks(8211),
                            CreatedUser = "APP",
                            CreatedUserId = 0,
                            IconName = "Doktorlar",
                            IsActive = true,
                            MenuDesctiption = "",
                            MenuName = "Doktorlar",
                            ModifiedDate = new DateTime(2024, 4, 6, 23, 33, 24, 916, DateTimeKind.Local).AddTicks(8211),
                            ModifiedUserId = 0,
                            ModifiedUserName = "APP"
                        });
                });

            modelBuilder.Entity("AkarSoftware.HospitalApp.Entities.Concrete.Identities.AppModules", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("AppModules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 4, 6, 23, 33, 24, 916, DateTimeKind.Local).AddTicks(8381),
                            CreatedUser = "APP",
                            CreatedUserId = 0,
                            Description = "Herkesin Gördüğü Tanıtım Sayfası İçeriklerini içermektedir ",
                            IsActive = true,
                            ModifiedDate = new DateTime(2024, 4, 6, 23, 33, 24, 916, DateTimeKind.Local).AddTicks(8382),
                            ModifiedUserId = 0,
                            ModifiedUserName = "APP",
                            Name = "Landing"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 4, 6, 23, 33, 24, 916, DateTimeKind.Local).AddTicks(8384),
                            CreatedUser = "APP",
                            CreatedUserId = 0,
                            Description = "Bilgi İşlem Direktörlüğü ve Şirket sahiplerinin erişebildiği bir Modül ",
                            IsActive = true,
                            ModifiedDate = new DateTime(2024, 4, 6, 23, 33, 24, 916, DateTimeKind.Local).AddTicks(8384),
                            ModifiedUserId = 0,
                            ModifiedUserName = "APP",
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("AkarSoftware.HospitalApp.Entities.Concrete.Identities.AppRoles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppRoles");
                });

            modelBuilder.Entity("AkarSoftware.HospitalApp.Entities.Concrete.Identities.AppRolesMenus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppMenusId")
                        .HasColumnType("int");

                    b.Property<int>("AppRoleId")
                        .HasColumnType("int");

                    b.Property<int>("AppRolesId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppMenusId");

                    b.HasIndex("AppRolesId");

                    b.ToTable("AppRolesMenus");
                });

            modelBuilder.Entity("AkarSoftware.HospitalApp.Entities.Concrete.Identities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BornDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<string>("EmailAdress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailAdressConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<int>("GendersId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePhoto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorAuth")
                        .HasColumnType("bit");

                    b.Property<string>("UserMailAdress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GendersId");

                    b.ToTable("AppUser");
                });

            modelBuilder.Entity("AkarSoftware.HospitalApp.Entities.Concrete.Identities.AppUserRoles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("RolesId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("RolesId");

                    b.ToTable("AppUserRoles");
                });

            modelBuilder.Entity("AkarSoftware.HospitalApp.Entities.Concrete.Identities.Genders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 4, 6, 23, 33, 24, 916, DateTimeKind.Local).AddTicks(8483),
                            CreatedUser = "APP",
                            CreatedUserId = 0,
                            IsActive = true,
                            ModifiedDate = new DateTime(2024, 4, 6, 23, 33, 24, 916, DateTimeKind.Local).AddTicks(8484),
                            ModifiedUserId = 0,
                            ModifiedUserName = "APP",
                            Name = "Erkek"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 4, 6, 23, 33, 24, 916, DateTimeKind.Local).AddTicks(8486),
                            CreatedUser = "APP",
                            CreatedUserId = 0,
                            IsActive = true,
                            ModifiedDate = new DateTime(2024, 4, 6, 23, 33, 24, 916, DateTimeKind.Local).AddTicks(8487),
                            ModifiedUserId = 0,
                            ModifiedUserName = "APP",
                            Name = "Kadın"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 4, 6, 23, 33, 24, 916, DateTimeKind.Local).AddTicks(8488),
                            CreatedUser = "APP",
                            CreatedUserId = 0,
                            IsActive = true,
                            ModifiedDate = new DateTime(2024, 4, 6, 23, 33, 24, 916, DateTimeKind.Local).AddTicks(8489),
                            ModifiedUserId = 0,
                            ModifiedUserName = "APP",
                            Name = "Belirtmek İstemiyor"
                        });
                });

            modelBuilder.Entity("AkarSoftware.HospitalApp.Entities.Concrete.Identities.AppMenus", b =>
                {
                    b.HasOne("AkarSoftware.HospitalApp.Entities.Concrete.Identities.AppModules", "AppModules")
                        .WithMany("AppMenus")
                        .HasForeignKey("AppModulesId");

                    b.HasOne("AkarSoftware.HospitalApp.Entities.Concrete.Identities.AppMenus", "RootMenus")
                        .WithMany("ChildMenus")
                        .HasForeignKey("RootMenusId");

                    b.Navigation("AppModules");

                    b.Navigation("RootMenus");
                });

            modelBuilder.Entity("AkarSoftware.HospitalApp.Entities.Concrete.Identities.AppRolesMenus", b =>
                {
                    b.HasOne("AkarSoftware.HospitalApp.Entities.Concrete.Identities.AppMenus", "AppMenus")
                        .WithMany("AppRolesMenus")
                        .HasForeignKey("AppMenusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AkarSoftware.HospitalApp.Entities.Concrete.Identities.AppRoles", "AppRoles")
                        .WithMany("AppRolesMenus")
                        .HasForeignKey("AppRolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppMenus");

                    b.Navigation("AppRoles");
                });

            modelBuilder.Entity("AkarSoftware.HospitalApp.Entities.Concrete.Identities.AppUser", b =>
                {
                    b.HasOne("AkarSoftware.HospitalApp.Entities.Concrete.Identities.Genders", "Genders")
                        .WithMany("AppUsers")
                        .HasForeignKey("GendersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genders");
                });

            modelBuilder.Entity("AkarSoftware.HospitalApp.Entities.Concrete.Identities.AppUserRoles", b =>
                {
                    b.HasOne("AkarSoftware.HospitalApp.Entities.Concrete.Identities.AppUser", "AppUser")
                        .WithMany("AppUserRoles")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AkarSoftware.HospitalApp.Entities.Concrete.Identities.AppRoles", "Roles")
                        .WithMany("AppUserRoles")
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("AkarSoftware.HospitalApp.Entities.Concrete.Identities.AppMenus", b =>
                {
                    b.Navigation("AppRolesMenus");

                    b.Navigation("ChildMenus");
                });

            modelBuilder.Entity("AkarSoftware.HospitalApp.Entities.Concrete.Identities.AppModules", b =>
                {
                    b.Navigation("AppMenus");
                });

            modelBuilder.Entity("AkarSoftware.HospitalApp.Entities.Concrete.Identities.AppRoles", b =>
                {
                    b.Navigation("AppRolesMenus");

                    b.Navigation("AppUserRoles");
                });

            modelBuilder.Entity("AkarSoftware.HospitalApp.Entities.Concrete.Identities.AppUser", b =>
                {
                    b.Navigation("AppUserRoles");
                });

            modelBuilder.Entity("AkarSoftware.HospitalApp.Entities.Concrete.Identities.Genders", b =>
                {
                    b.Navigation("AppUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
